export const carFeaturesData = [
    'Bluetooth',
    'GPS System',
    'Backup camera',
    'Keyless entry',
    'Push-button start',
    'Cruise control',
    'Leather seats',
    'Heated seats',
    'Power windows',
    'Power mirrors',
    'Power door locks',
    'Sunroof/moonroof',
    'Alloy wheels',
    'LED headlights',
    'Fog lights',
    'Parking sensors',
    'Wireless charging',
    'USB ports',
    'Premium sound system',
    'Power-adjustable seats',
    'Memory seats',
    'Heated steering wheel',
    'Remote start',
    'Rain-sensing wipers',
    'Heads-up display',
    '360-degree camera',
    'Towing package',
    'Off-road capability',
    'Four-wheel drive',
    'All-wheel drive',
    'Front-wheel drive',
    'Rear-wheel drive',
    'Sports suspension',
    'Turbocharged engine',
    'Convertible top',
    'Self-parking feature'
  ];
  