export const transmissionsData = [
    'Manual',
    'Automatic',
    'CVT (Continuously Variable Transmission)',
    'DSG (Direct-Shift Gearbox)',
    'Tiptronic',
    'PDK (Porsche Doppelkupplung)',
    'DCT (Dual-Clutch Transmission)',
    'AMT (Automated Manual Transmission)',
    'e-CVT (Electronic Continuously Variable Transmission)',
    'Hybrid Transmission',
    'Torque Converter Automatic',
    'Semi-Automatic',
    'Sequential Manual',
    'Automated Clutch',
    'Variomatic',
    'Xtronic CVT',
    'iMT (Intelligent Manual Transmission)',
    'e-DCT (Electronically Controlled Dual-Clutch Transmission)',
    'SportShift',
    'S-Tronic',
    'Steptronic',
    'Lineartronic',
];
